# Generated by Django 4.2.7 on 2024-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_bb__content_rendered_alter_bb_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='_content_rendered',
        ),
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, default='Какое-то значение:', null=True, verbose_name='Описание'),
        ),
    ]
