# Generated by Django 4.2.7 on 2024-02-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
